version: "3"

services:
    app:
        container_name: test
        image: lazerg/laravel:php81
        working_dir: /var/www/app
        ports:
            - 8000:8000
        volumes:
            - .:/var/www/app
        command: sleep infinity
